Add song statistics page
Yooooomi/your_spotify pull request #194
Opened 2023-01-28 08:46 UTC by michaelkennethdavid

Song statistics page
- Times listened
- Last listened on
- First listened on
- Artist
- Album
- Top two months
- Recently played on

![song_7gZ3kWNtIxFgxjsm5OTVMB](https://user-images.githubusercontent.com/55848461/215256213-49c19e41-ad9c-4022-8e9d-0df08a501b40.png)

https://user-images.githubusercontent.com/55848461/215256441-fb6850da-2269-40dc-8dc4-d16ecccbc635.mp4

2023-01-28 08:48 UTC, Yooooomi commented
I think I'll love what I'll see in there. I'll review in an hour. Already thanks for the work, you're sick

2023-01-28 21:09 UTC, Yooooomi commented
I had a quick look. Insane job, glad to see you understood how it works. There is a few duplications of code but I'll fix that. I'm on holidays for the week. I'll work on it when I get back. Thanks again.

2023-01-29 05:38 UTC, michaelkennethdavid commented
Awesome, feel free to modify it. Thanks!

2023-01-29 08:56 UTC, NeoHBz commented
Great work @michaelkennethdavid 

@Yooooomi I guess this can also implement #127  (?)

2023-01-29 13:21 UTC, Yooooomi commented
Don't know, might want to be able to delete artists, albums, tracks etc

2023-02-05 15:05 UTC, Yooooomi requested changes
I commented out to keep track of what I have to change. Nice work, I'll fix the few things and merge it for the next release. Thanks again :)

2023-02-05 15:05 UTC, Yooooomi commented on client/src/scenes/Tops/Songs/Track/Track.tsx
> +          <InlineTrack key={track.id} track={track} />{' '}
key should not be necessary here

2023-02-05 15:05 UTC, Yooooomi commented on client/src/scenes/TrackStats/TrackRank/TrackRank.tsx
> +  }, [tracks, ids]);
a useTracks(trackIds) would be cleaner

2023-02-05 15:05 UTC, Yooooomi commented on client/src/scenes/TrackStats/TrackRank/TrackRank.tsx
> +          <InlineTrack track={getTrack(rank.id)!} />
while this should always be good, it's unsafe, it might be better to display nothing than crashing

2023-02-05 15:05 UTC, Yooooomi commented on server/src/routes/track.ts
> +      }
this is not consistent, the route below returns 404 if it does not find the song, here you return 200. For the artist, the NEVER_LISTENED code is returned if the total number of listens is equal to 0

2023-02-05 15:19 UTC, Yooooomi commented
History is not built of InlineTracks

2023-02-10 22:59 UTC, merged