feat: rework sider design
Yooooomi/your_spotify pull request #360
Opened 2024-03-02 16:43 UTC by quentinguidee

Some design refinements for the drawer

| Before | After |
| --- | --- |
| <img width="248" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/12123721/d6d5914a-5d8f-4654-8f8f-6f695bb8b95b"> | <img width="248" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/12123721/dd3ffb9a-4ee6-4d19-bd92-0789c17c04b4"> |

| Before | After |
| --- | --- |
| <img width="248" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/12123721/47bd2b57-7885-4d02-8a63-950b8d0a3882"> | <img width="248" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/12123721/26e7acba-6966-41e1-9694-c86cc879a13f"> |

2024-03-02 16:54 UTC, Yooooomi commented
Dude you got no chill haha. It seems cool. Is light mode working as intended? Is responsive still ok?

2024-03-02 16:59 UTC, quentinguidee commented
Here are screenshots for dark mode:

<img width="246" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/12123721/023d283a-0ff1-4d0b-a8c7-940350d136cd">
<img width="249" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/12123721/8b9e053a-942b-42f3-9276-179f0d43c3d6">

And responsive seems to work fine!

2024-03-02 17:48 UTC, maaaathis commented
It looks really good 👍
The only thing I've never fully understood is the state of the current page. The red text differs greatly from the hover state. But idk.

2024-03-02 17:50 UTC, Yooooomi commented
I guess we can just have the hover state persist when on the page

2024-03-02 17:54 UTC, maaaathis commented
> I guess we can just have the hover state persist when on the page

A bit darker or lighter, but yes.

2024-03-02 17:55 UTC, Yooooomi commented
Lighter on dark mode, darker on light mode

2024-03-02 18:05 UTC, Yooooomi requested changes

2024-03-02 18:05 UTC, Yooooomi commented on apps/client/src/components/Layout/Sider/SiderCategory/index.module.css
> +  background: rgba(255, 255, 255, 0.2);
You should variabilise this in index.css, so that we can provide light and dark variants. Named something like link-hover-background

2024-03-02 18:05 UTC, Yooooomi commented on apps/client/src/components/SiderSearch/index.module.css
> +  background: rgba(255, 255, 255, 0.25);
This is very close to the other color

2024-03-02 18:27 UTC, quentinguidee commented
This way?

https://github.com/Yooooomi/your_spotify/assets/12123721/047f9b42-642f-4aa3-9261-2993871dc0da

2024-03-02 18:38 UTC, Yooooomi commented
Maybe full white written in black when focused

2024-03-02 18:44 UTC, maaaathis commented
> Maybe full white written in black when focused

Thats the same too big contrast as on the search before.

2024-03-10 12:20 UTC, Yooooomi approved these changes

2024-03-10 12:20 UTC, merged