Add audio features
Yooooomi/your_spotify pull request #383
Opened 2024-03-24 19:20 UTC by bloedboemmel

Added audio_features to the song-stats.

<img width="1690" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/58067119/9604c524-dd89-4307-86d0-33b6e94f08fd">

I will add more stats soon, but still need to get a better understanding of the overall api-usage.

2024-03-24 19:42 UTC, Yooooomi requested changes

2024-03-24 19:42 UTC, Yooooomi commented on apps/client/src/index.css
> +  margin-bottom: 10px;
must be 2, or multiples of 4

2024-03-24 19:42 UTC, Yooooomi commented on apps/client/src/scenes/TrackStats/TrackStats.tsx
> +                      </Text>
is this required, nested text?

2024-03-24 19:42 UTC, Yooooomi commented on apps/client/src/scenes/TrackStats/TrackStats.tsx
> +                      </Text>
same

2024-03-24 19:42 UTC, Yooooomi commented on apps/client/src/scenes/TrackStats/TrackStats.tsx
> +                      </Text>
same, etc.

2024-03-24 19:42 UTC, Yooooomi commented on apps/client/src/services/stats.ts
> +}
i'll have to migrate this to the new date formatter

2024-03-24 19:42 UTC, Yooooomi commented on apps/client/src/services/types.ts
> +  id?: string;
i dont know if this is needed

2024-03-24 19:42 UTC, Yooooomi commented on apps/client/src/services/types.ts
> +  analysis_url?: string;
not sure about all of this, will see Spotify API if we really need this

2024-03-24 19:42 UTC, Yooooomi commented on apps/server/src/database/schemas/audioFeatures.ts
> +}
same here

2024-03-24 19:42 UTC, Yooooomi commented on apps/server/src/database/schemas/track.ts
> +    audio_features: Object,
not safe

2024-03-24 19:42 UTC, Yooooomi commented on apps/server/src/migrations/1710176947000-add_audio_features.ts
> +    for await (const user of UserModel.find()) {
you dont need to loop users here

2024-03-24 19:42 UTC, Yooooomi commented on apps/server/src/migrations/1710176947000-add_audio_features.ts
> +        }
this will explode for large databases, or low ram devices

2024-03-24 19:42 UTC, Yooooomi commented on apps/server/src/migrations/1710176947000-add_audio_features.ts
> +                track.audio_features = trackAudioFeaturesSmall;
would prefer to create the type instead of filtering unwanted types. and it is not safe if spotify adds new fields

2024-03-24 19:42 UTC, Yooooomi commented on apps/server/src/spotify/dbTools.ts
> +const AudioFeaturesUrl = "https://api.spotify.com/v1/audio-features";
no uppercase here, or const outside scope in UPPERCASE

2024-03-24 19:42 UTC, Yooooomi commented on apps/server/src/spotify/dbTools.ts
> +  const AudioFeatures = await getIdsHandlingMax<AudioFeatures>(
no uppercase here

2024-03-24 19:42 UTC, Yooooomi commented on apps/server/src/spotify/dbTools.ts
> +    const trackAudioFeatures = AudioFeatures.find(feature => feature && feature.id === track.id);
weird first condition

2024-03-24 19:42 UTC, Yooooomi commented on apps/server/src/spotify/dbTools.ts
> +      track.audio_features = trackAudioFeaturesSmall
same here as above

2024-03-24 19:45 UTC, Yooooomi commented
Hey, really nice work!
I am not sure about the design in the track page, but this is interesting to have audio feature in the track for now and the future.
We cannot wait for the migration to end before launching the server, for huge databases it would take days. I think we need more something like a flag when all tracks are processed in the database, and then enable audio feature related stats in the app.
Dont feel forced to fix all the comments i did on the pull request. I can take care of them, you already did a huge work and thanks for this.

2024-11-29 16:55 UTC, tigattack commented
I was really looking forward to this, but Spotify have just locked down a bunch of their API endpoints, including those relied upon in this PR: https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api

2024-12-12 16:37 UTC, bloedboemmel commented
Damn, I forgot about this!
And now there are these bad news. Luckily we didn't merge this. It would be a mess to roll back :)

2024-12-12 16:37 UTC, closed without merging